import { colors, duration, easing, fonts, gradient, light, radius } from "@nanohype/tokens";

/**
 * The error-page stylesheet, resolved from `@nanohype/tokens`.
 *
 * Why a separate stylesheet and not an inline `<style>`: the CSP is
 * `style-src 'self'` (no `'unsafe-inline'`), which blocks inline `<style>` and
 * `style=` attributes. A same-origin `<link>` is allowed as-is, needs no CSP
 * change on any site, and is edge-cached so it survives an origin blip while a
 * 5xx page is being served.
 *
 * Why no `.dark` class or theme script: a strict `script-src 'self'` blocks the
 * inline pre-paint script too, and an error page is often a visitor's first hit
 * (empty localStorage). So light/dark follows the OS via `prefers-color-scheme`
 * — zero JS, no flash.
 *
 * Note the inversion against the rest of the estate. `tokens.css` ships dark as
 * the default and `html.light` as the override, because an app can run a
 * pre-paint script and pick. With no script to run, the media query decides, so
 * the light values go in `:root` and the dark ones in the query. Same token
 * values either way — only which block holds which changes.
 */
export function buildErrorCss(): string {
  return `/* Generated by @nanohype/error-pages from @nanohype/tokens. Do not edit. */
:root {
  color-scheme: light dark;
${declarations(light)}
  --gradient-brand: ${gradient.brand};
  --radius: ${radius.lg};
  --font-sans: ${fonts.sans};
  --font-mono: ${fonts.mono};
  --ease-out: ${easing.out};
  --duration-slow: ${duration.slow};
}

@media (prefers-color-scheme: dark) {
  :root {
${declarations(colors)}
  }
}

*,
*::before,
*::after {
  box-sizing: border-box;
}

html {
  -webkit-text-size-adjust: 100%;
}

body {
  margin: 0;
  min-height: 100vh;
  min-height: 100svh;
  display: grid;
  place-items: center;
  padding: 2rem 1.5rem;
  background: var(--background);
  color: var(--foreground);
  font-family: var(--font-sans);
  font-size: 15px;
  line-height: 1.5;
  letter-spacing: -0.006em;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

main {
  width: 100%;
  max-width: 30rem;
  text-align: center;
  animation: rise var(--duration-slow) var(--ease-out) both;
}

.code {
  font-size: clamp(4.5rem, 18vw, 7rem);
  line-height: 1;
  font-weight: 600;
  letter-spacing: -0.04em;
  background: var(--gradient-brand);
  -webkit-background-clip: text;
  background-clip: text;
  /* The solid colour is the fallback: a browser without background-clip: text
     paints this instead of a transparent numeral on a transparent fill. */
  color: var(--primary);
  -webkit-text-fill-color: transparent;
}

.eyebrow {
  margin: 0 0 1.25rem;
  font-family: var(--font-mono);
  font-size: 0.75rem;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: var(--dim);
}

h1 {
  margin: 1rem 0 0.5rem;
  font-size: 1.375rem;
  font-weight: 600;
  letter-spacing: -0.02em;
  color: var(--foreground);
}

p {
  margin: 0 auto;
  max-width: 24rem;
  color: var(--muted-foreground);
}

.actions {
  margin-top: 1.75rem;
}

.button {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.55rem 1.1rem;
  border-radius: var(--radius);
  background: var(--primary);
  color: var(--primary-foreground);
  font-size: 0.875rem;
  font-weight: 500;
  text-decoration: none;
  border: 1px solid transparent;
  transition:
    filter var(--duration-slow) var(--ease-out),
    transform var(--duration-slow) var(--ease-out);
}

.button:hover {
  filter: brightness(1.06);
}

.button:active {
  transform: scale(0.97);
}

.button:focus-visible {
  outline: 2px solid var(--ring);
  outline-offset: 2px;
}

@keyframes rise {
  from {
    opacity: 0;
    transform: translateY(0.5rem);
  }
  to {
    opacity: 1;
    transform: none;
  }
}

@media (prefers-reduced-motion: reduce) {
  main {
    animation: none;
  }
  .button {
    transition: none;
  }
}
`;
}

function declarations(vars: Record<string, string>): string {
  return Object.entries(vars)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");
}
