apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "__PROJECT_NAME__.fullname" . }}-grafana-datasources
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "__PROJECT_NAME__.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "__PROJECT_NAME__.fullname" . }}-prometheus:{{ .Values.prometheus.service.port }}
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          httpMethod: POST
      - name: Loki
        type: loki
        access: proxy
        url: http://{{ include "__PROJECT_NAME__.fullname" . }}-loki:{{ .Values.loki.service.port }}
        editable: false
        jsonData:
          maxLines: 1000
