apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "__PROJECT_NAME__.componentName" (list "historical" .) }}
  labels:
    {{- include "__PROJECT_NAME__.componentLabels" (list "historical" .) | nindent 4 }}
spec:
  serviceName: {{ include "__PROJECT_NAME__.componentName" (list "historical" .) }}
  replicas: {{ .Values.historical.replicas }}
  selector:
    matchLabels:
      {{- include "__PROJECT_NAME__.componentSelectorLabels" (list "historical" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "__PROJECT_NAME__.componentSelectorLabels" (list "historical" .) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "__PROJECT_NAME__.fullname" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: historical
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["historical"]
          ports:
            - name: http
              containerPort: {{ .Values.historical.service.port }}
              protocol: TCP
            - name: prometheus
              containerPort: 9000
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DRUID_METADATA_STORAGE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.metadata }}
                  key: username
            - name: DRUID_METADATA_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.metadata }}
                  key: password
            - name: DRUID_METADATA_STORAGE_CONNECT_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.metadata }}
                  key: uri
            - name: DRUID_DEEP_STORAGE_BUCKET
              value: {{ .Values.deepStorage.bucket | quote }}
            - name: DRUID_INDEX_LOGS_BUCKET
              value: {{ .Values.deepStorage.indexLogsBucket | quote }}
          volumeMounts:
            - name: common-conf
              mountPath: /opt/druid/conf/druid/cluster/_common
              readOnly: true
            - name: component-conf
              mountPath: /opt/druid/conf/druid/cluster/data/historical
              readOnly: true
            - name: scratch
              mountPath: /var/druid
            - name: segment-cache
              mountPath: /var/druid/segment-cache
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 180
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
          resources:
            {{- toYaml .Values.historical.resources | nindent 12 }}
      volumes:
        - name: common-conf
          configMap:
            name: {{ include "__PROJECT_NAME__.fullname" . }}-common
        - name: component-conf
          configMap:
            name: {{ include "__PROJECT_NAME__.componentName" (list "historical" .) }}-conf
        - name: scratch
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: segment-cache
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.historical.storage.size }}
