import { metrics } from "@opentelemetry/api";

// ── Billing Metrics ───────────────────────────────────────────────
//
// OTel counters and histograms for billing observability. Tracks
// usage recording, invoice generation, and payment totals. No-ops
// unless an OTel SDK is wired in by the consumer.
//

const meter = metrics.getMeter("__PROJECT_NAME__");

/** Total usage events recorded, labeled by metric name. */
export const billingUsageRecorded = meter.createCounter("billing_usage_recorded", {
  description: "Total usage events recorded by metric name",
});

/** Total invoices generated, labeled by status. */
export const billingInvoiceGenerated = meter.createCounter("billing_invoice_generated", {
  description: "Total invoices generated by status",
});

/** Total payment amount processed, labeled by result (success or failure). */
export const billingPaymentTotal = meter.createCounter("billing_payment_total", {
  description: "Total payment amount processed in smallest currency unit",
  unit: "cents",
});
