{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "__PROJECT_NAME__.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "__PROJECT_NAME__.labels" . | nindent 4 }}
{{- end }}
