apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: __PROJECT_NAME__-require-jwt
  namespace: __NAMESPACE__
  labels:
    app.kubernetes.io/name: __PROJECT_NAME__
    app.kubernetes.io/component: istio-policy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: __PROJECT_NAME__
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals:
              - "__OIDC_ISSUER__/*"
      when:
        - key: request.auth.claims[aud]
          values:
            - __ALLOWED_AUD__
