# Production delta — only differences from values.yaml.
image:
  tag: production

replicaCount: 3

commonLabels:
  platform.nanohype.dev/environment: production

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# externalSecret:
#   remoteRefSecret: __APP_NAME__/production/app-secrets
