# Staging delta — only differences from values.yaml.
image:
  tag: staging

replicaCount: 2

commonLabels:
  platform.nanohype.dev/environment: staging

# externalSecret:
#   remoteRefSecret: __APP_NAME__/staging/app-secrets
